### ISSUE TITLE
Wrong min/max on empty entries of CompressedIntegerLists 

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/IRanges#10]
Consider the following:

```r
library(IRanges)
a <- list(integer(0), 1L, 1:2, 1:3)
b <- IntegerList(a, compress=TRUE)
max(b)
# [1] -2147483647           1           2           3
min(b)
# [1] 2147483647          1          1          1
```

I can smell the C here. Presumably these big numbers are meant to be `NA_integer_`s.

<details>
<summary>Session info</summary>

```
R version 3.5.3 RC (2019-03-04 r76215)
Platform: x86_64-apple-darwin17.7.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /Users/luna/Software/R/R-3-5-branch/lib/libRblas.dylib
LAPACK: /Users/luna/Software/R/R-3-5-branch/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets
[8] methods   base

other attached packages:
[1] IRanges_2.16.0      S4Vectors_0.20.1    BiocGenerics_0.28.0

loaded via a namespace (and not attached):
[1] compiler_3.5.3 tools_3.5.3
```
</details>

**Comment by hpages** [comment]
Hi Aaron,

Note that this is already being discussed [here](https://github.com/Bioconductor/IRanges/issues/5). Note that returning the smallest or greatest integer here was intended. It provides a semantic that is as close as it can be to that of `sapply(a, max)` and `sapply(a, min)` but with the result being **always** an integer vector. The other 2 options are returning `NA_integer_` like you're proposing above, or returning `-Inf` and `Inf` like proposed by @LiNk-NY and @lawremi (see issue #5). Each of the 3 options could also issue a warning when a list element is empty so this gives us a total of 6 options.

I'm generally strongly in favor of preserving consistency with base R, which in this case means doing `-Inf` and `Inf` (with a warning), but I also find the switch from integer to double really ugly. So it's one of these rare situations where I think it's ok to diverge from base R.

So what should we do gentlemen? I vote for not changing anything.

H.

**Comment by lawremi** [comment]
I agree, let's keep the current behavior. Returning an extreme value is more useful downstream than an `NA` value. Unfortunately extreme integer values just look ugly.

**Comment by LTLA** [comment]
Whoops. Didn't know how I missed #5. Closing.
