### ISSUE TITLE
unname does not work for SplitDFLists

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/IRanges#25]
```r
library(IRanges)
df <- DataFrame(X=1:10)
out <- split(df, factor(1:10))
unname(out)
## Error in `dimnames<-`(`*tmp*`, value = NULL) : 
##   replacement value must be a list
```

Probably because it has non-`NULL` `dimnames()` and so `unname` gets confused. Easy solution would be to turn `unname` into a generic and then just remove the names. If `force=TRUE`, you could also strip the underlying dimnames in the DFrames.

**Comment by lawremi** [comment]
Should be fixed in S4Vectors 0.29.4.
