### ISSUE TITLE
startsWith and endsWith are not exported

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/IRanges#26]
Is this an oversight, or intentional? 

```r
library(IRanges)
X <- CharacterList(split(LETTERS, 1:26))
startsWith(X, "A")
## Error in startsWith("A", X) : non-character object(s)
IRanges:::startsWith(X, "A") ## works
```

**Comment by hpages** [comment]
@lawremi Michael? You added the `startsWith()` and `endsWith()` methods (commit 52bc2e49d00ade015656b225b6b2533800ece075). Thx

**Comment by lawremi** [comment]
Yes, it was intentional, to avoid the need to support them, but I guess that was unsuccessful ;)
