### ISSUE TITLE
Cannot install IRanges with BiocManager::install("IRanges")

### ISSUE THREAD

**Issue by raphaelbetschart** [Bioconductor/IRanges#32]
I am having trouble with the latest version of IRanges (2.24.0). I could not create IRanges objects, so I deinstalled the package. But when I now want to install it I always get the following error:

Error in reconcilePropertiesAndPrototype(name, slots, prototype, superClasses,  : 
  no definition was found for superclass “DataTable” in the specification of class “RangedData”
Error: unable to load R code in package ‘IRanges’
Execution halted

I do not know what this error means, could you help me?

Thanks,
Raphael

**Comment by mtmorgan** [comment]
This is  likely because of a version mismatch in your packages -- run `BiocManager::valid()` and update accordingly. Please also use the support site https://support.bioconductor.org for 'user-oriented' help questions. Please report here if successful, and close the issue.

**Comment by raphaelbetschart** [comment]
Looks like there was something wrong with my BioCManager I ran `BiocManager::install(version = "3.12")`, which solved the problem. I did not know about [https://support.bioconductor.org ](url), thanks for linking it.
