### ISSUE TITLE
quantile,AtomicList-method misbehaves for length(p)==1

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/IRanges#33]
```r
library(IRanges)
out <- NumericList(A=1:5, B=2:6)
quantile(out)
##      A B
## 0%   1 2
## 25%  2 3
## 50%  3 4
## 75%  4 5
## 100% 5 6
```

Okay, so far so good. Quantiles on the rows, list elements in the columns. But then:

```r
quantile(out, p=0.5)
## A.50% B.50% 
##     3     4 
```

I would have expected:

```
##     A B
## 50% 3 4
```

which preserves the expectations of the output structure, and also gets the names right.

Some poking around indicates that the offender is the overly liberal `sapply` at:

https://github.com/Bioconductor/IRanges/blob/8633595e4512f2158d25dde2b0fd2041080f342a/R/CompressedAtomicList-class.R#L400

and 

https://github.com/Bioconductor/IRanges/blob/8633595e4512f2158d25dde2b0fd2041080f342a/R/AtomicList-utils.R#L69

**Comment by lawremi** [comment]
The issue is at the latter example (`quantile()` is not part of the `Summary()` group). I will fix this soon.

**Comment by hpages** [comment]
Isn't it interesting that the `quantile()` method for AtomicList is implemented as `do.call(rbind, lapply(x, quantile, ...))` and that the test for it is `checkIdentical(quantile(list1, na.rm=TRUE), do.call(rbind, lapply(list1, quantile, na.rm=TRUE)))`?
