### ISSUE TITLE
Constructing a CompressedList given the PartitioningByEnd object?

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/IRanges#36]
If I have the `unlistData` and a `PartitioningByEnd` object, how do I construct the associated `CompressedList`? I come across this situation on occasion where I already know that the `unlistData` is in the correct order and I know the runs associated with each `List` element; it seems like a waste to have to create a `rep(seq_along(runs), runs)` factor to use `splitAsList()`.

**Comment by hpages** [comment]
`relist()`?

**Comment by LTLA** [comment]
Thanks, that works. Not easy to find in the `?CompressedList` docs, though. I need to navigate to `?"relist,ANY,PartitioningByEnd-method"` at which point I might as well already know about this function.

**Comment by hpages** [comment]
I added something to `?CompressedList`. This is in **IRanges** 2.25.7
