### ISSUE TITLE
Unfortunately indecipherable C error on install

### ISSUE THREAD

**Issue by mollysrour** [Bioconductor/IRanges#45]
Hi all, 

I'm an R coder and have no experience with C. When I try to install IRanges, I receive this error (no matter the version): 

`In file included from CompressedAtomicList_utils.c:5:
IRanges.h:100:15: error: unknown type name ‘IntPairAE’
  100 |         const IntPairAE *intpair_ae
      |               ^~~~~~~~~
IRanges.h:105:15: error: unknown type name ‘IntPairAEAE’
  105 |         const IntPairAEAE *intpair_aeae
      |               ^~~~~~~~~~~
IRanges.h:233:1: error: unknown type name ‘Ints_holder’; did you mean ‘IRanges_holder’?
  233 | Ints_holder _get_elt_from_CompressedIntsList_holder(
      | ^~~~~~~~~~~
      | IRanges_holder` 
      
Does anyone have any insight here?

**Comment by hpages** [comment]
Unfortunately indecipherable and impossible to reproduce issue. Glad you were able to sort it out :wink:
