### ISSUE TITLE
R 4.3.3 Unable to install IRanges

### ISSUE THREAD

**Issue by Tang-pro** [Bioconductor/IRanges#52]
Hi, @lawremi 
![image](https://github.com/Bioconductor/IRanges/assets/149154213/f69a91f9-98c1-4304-aa48-6669189f4a0b)
How to solve it? please

**Comment by hpages** [comment]
Please show the exact command you used to install the package, plus the full output of the command. Copy-paste them here preceded and followed by triple-backtick lines (click on the Preview tab to see how this will render). Do NOT provide a screenshot! Finally, provide the output of your `sessionInfo()` (also preceded and followed by triple-backtick lines).

FYI **IRanges** is a Bioconductor package and the only supported/reliable way to install Bioconductor packages is with `BiocManager::install()`. In particular this is the only method that knows how to pick up the version of **IRanges** that matches your version of Bioconductor. Other installation methods tend to mix-up packages from various versions of Bioconductor, which almost never ends well. See https://bioconductor.org/packages/IRanges
 
Thanks!

**Comment by Tang-pro** [comment]
Hi, @hpages 
`library(BiocManager) `
`options("repos" = c(CRAN="https://mirrors.tuna.tsinghua.edu.cn/CRAN/"))`
`options(BioC_mirror="https://mirrors.tuna.tsinghua.edu.cn/bioconductor") `
`BiocManager::install("IRanges")`

installation of package ‘IRanges' had non-zero exit status 
I just tested it and it was successful. It's probably due to the network.
Thank you!
