### ISSUE TITLE
version bump required

### ISSUE THREAD

**Issue by FelixErnst** [Bioconductor/IRanges#9]
Hi

since the beginning of January, the version number of the `IRanges` package was not increased. This causes the latest changes not to be propagated to the `SPB`, which leads to a build error during the submission of the package `Structstrings`.

Would it be possible to bump the version number, so that an update of the `IRanges` package is triggered on the `SPB`?

Thanks for any help in advance.

**Comment by hpages** [comment]
[Done](https://github.com/Bioconductor/IRanges/commit/7b00d37c32b1e0b762f20b2a5d01ef6900c61beb)
